CREATE TABLE IF NOT EXISTS hospital (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hn VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
