package seeds

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"time"
)

// PatientSeed represents realistic patient mockup data.
type PatientSeed struct {
	HospitalHN   string
	PatientHN    string
	NationalID   string
	PassportID   string
	FirstNameTH  string
	MiddleNameTH string
	LastNameTH   string
	FirstNameEN  string
	MiddleNameEN string
	LastNameEN   string
	DateOfBirth  string // Format: YYYY-MM-DD
	PhoneNumber  string
	Email        string
	Gender       string
}

// DefaultPatients contains realistic mockup patients across hospitals for testing /patient/search.
var DefaultPatients = []PatientSeed{
	// =========================================================================
	// HOSP001: โรงพยาบาลศิริราช (Siriraj Hospital) - 25 Patients
	// (Supports pagination testing: page 1 with limit 20, page 2 with offset 20)
	// =========================================================================
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00001",
		NationalID:   "1100501234567",
		PassportID:   "",
		FirstNameTH:  "สมชาย",
		MiddleNameTH: "วิชัย",
		LastNameTH:   "ใจดี",
		FirstNameEN:  "Somchai",
		MiddleNameEN: "Wichai",
		LastNameEN:   "Jaidee",
		DateOfBirth:  "1985-04-12",
		PhoneNumber:  "0812345678",
		Email:        "somchai.jaidee@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00002",
		NationalID:   "1100507654321",
		PassportID:   "AA9876543",
		FirstNameTH:  "สมหญิง",
		MiddleNameTH: "",
		LastNameTH:   "สุขใจ",
		FirstNameEN:  "Somying",
		MiddleNameEN: "",
		LastNameEN:   "Sukjai",
		DateOfBirth:  "1990-11-23",
		PhoneNumber:  "0823456789",
		Email:        "somying.sukjai@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00003",
		NationalID:   "",
		PassportID:   "US123456789",
		FirstNameTH:  "จอห์น",
		MiddleNameTH: "วิลเลียม",
		LastNameTH:   "สมิธ",
		FirstNameEN:  "John",
		MiddleNameEN: "William",
		LastNameEN:   "Smith",
		DateOfBirth:  "1978-08-15",
		PhoneNumber:  "0834567890",
		Email:        "john.smith@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00004",
		NationalID:   "1100502233445",
		PassportID:   "",
		FirstNameTH:  "สมใจ",
		MiddleNameTH: "",
		LastNameTH:   "ใจดี",
		FirstNameEN:  "Somjai",
		MiddleNameEN: "",
		LastNameEN:   "Jaidee",
		DateOfBirth:  "1992-03-10",
		PhoneNumber:  "0813334444",
		Email:        "somjai.jaidee@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00005",
		NationalID:   "1100503344556",
		PassportID:   "TH1122334",
		FirstNameTH:  "สมศักดิ์",
		MiddleNameTH: "บุญส่ง",
		LastNameTH:   "วัฒนพาณิชย์",
		FirstNameEN:  "Somsak",
		MiddleNameEN: "Bunsong",
		LastNameEN:   "Wattanapanich",
		DateOfBirth:  "1965-07-25",
		PhoneNumber:  "0814445555",
		Email:        "somsak.w@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00006",
		NationalID:   "1100504455667",
		PassportID:   "",
		FirstNameTH:  "สมบูรณ์",
		MiddleNameTH: "",
		LastNameTH:   "รุ่งเรือง",
		FirstNameEN:  "Somboon",
		MiddleNameEN: "",
		LastNameEN:   "Rungruang",
		DateOfBirth:  "1972-12-05",
		PhoneNumber:  "0815556666",
		Email:        "somboon.r@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00007",
		NationalID:   "1100505566778",
		PassportID:   "",
		FirstNameTH:  "กิตติพงษ์",
		MiddleNameTH: "วิวัฒน์",
		LastNameTH:   "เจริญผล",
		FirstNameEN:  "Kittipong",
		MiddleNameEN: "Wiwat",
		LastNameEN:   "Charoenphon",
		DateOfBirth:  "1988-09-18",
		PhoneNumber:  "0816667777",
		Email:        "kittipong.c@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00008",
		NationalID:   "1100506677889",
		PassportID:   "",
		FirstNameTH:  "กานดา",
		MiddleNameTH: "",
		LastNameTH:   "เจริญผล",
		FirstNameEN:  "Kanda",
		MiddleNameEN: "",
		LastNameEN:   "Charoenphon",
		DateOfBirth:  "1994-01-30",
		PhoneNumber:  "0817778888",
		Email:        "kanda.c@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00009",
		NationalID:   "1100507788990",
		PassportID:   "",
		FirstNameTH:  "นพดล",
		MiddleNameTH: "เฉลิมชัย",
		LastNameTH:   "มีสุข",
		FirstNameEN:  "Noppadol",
		MiddleNameEN: "Chaloemchai",
		LastNameEN:   "Meesuk",
		DateOfBirth:  "1980-05-14",
		PhoneNumber:  "0818889999",
		Email:        "noppadol.m@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00010",
		NationalID:   "1100508899001",
		PassportID:   "",
		FirstNameTH:  "ปรียา",
		MiddleNameTH: "",
		LastNameTH:   "สุขเกษม",
		FirstNameEN:  "Preeya",
		MiddleNameEN: "",
		LastNameEN:   "Sukkasem",
		DateOfBirth:  "1998-04-02",
		PhoneNumber:  "0821112222",
		Email:        "preeya.s@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00011",
		NationalID:   "1100509900112",
		PassportID:   "",
		FirstNameTH:  "วาสนา",
		MiddleNameTH: "",
		LastNameTH:   "ภักดี",
		FirstNameEN:  "Wassana",
		MiddleNameEN: "",
		LastNameEN:   "Phakdi",
		DateOfBirth:  "1983-06-20",
		PhoneNumber:  "0822223333",
		Email:        "wassana.p@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00012",
		NationalID:   "1100500011223",
		PassportID:   "",
		FirstNameTH:  "ประพันธ์",
		MiddleNameTH: "เกียรติศักดิ์",
		LastNameTH:   "รัตนไพศาล",
		FirstNameEN:  "Praphan",
		MiddleNameEN: "Kiattisak",
		LastNameEN:   "Ratanapaisan",
		DateOfBirth:  "1958-10-10",
		PhoneNumber:  "0823334444",
		Email:        "praphan.r@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00013",
		NationalID:   "1100501122334",
		PassportID:   "",
		FirstNameTH:  "ดวงใจ",
		MiddleNameTH: "",
		LastNameTH:   "รัตนไพศาล",
		FirstNameEN:  "Duangjai",
		MiddleNameEN: "",
		LastNameEN:   "Ratanapaisan",
		DateOfBirth:  "1962-02-14",
		PhoneNumber:  "0824445555",
		Email:        "duangjai.r@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00014",
		NationalID:   "1100502233446",
		PassportID:   "",
		FirstNameTH:  "อภิสิทธิ์",
		MiddleNameTH: "",
		LastNameTH:   "ทองหล่อ",
		FirstNameEN:  "Abhisit",
		MiddleNameEN: "",
		LastNameEN:   "Thonglor",
		DateOfBirth:  "1975-08-08",
		PhoneNumber:  "0825556666",
		Email:        "abhisit.t@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00015",
		NationalID:   "1100503344557",
		PassportID:   "",
		FirstNameTH:  "ศิริพร",
		MiddleNameTH: "",
		LastNameTH:   "ทองหล่อ",
		FirstNameEN:  "Siriporn",
		MiddleNameEN: "",
		LastNameEN:   "Thonglor",
		DateOfBirth:  "1977-11-19",
		PhoneNumber:  "0826667777",
		Email:        "siriporn.t@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00016",
		NationalID:   "",
		PassportID:   "US987654321",
		FirstNameTH:  "ซาร่าห์",
		MiddleNameTH: "เจน",
		LastNameTH:   "คอนเนอร์",
		FirstNameEN:  "Sarah",
		MiddleNameEN: "Jane",
		LastNameEN:   "Connor",
		DateOfBirth:  "1984-05-12",
		PhoneNumber:  "0827778888",
		Email:        "sarah.connor@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00017",
		NationalID:   "",
		PassportID:   "GB112233445",
		FirstNameTH:  "ไมเคิล",
		MiddleNameTH: "เดวิด",
		LastNameTH:   "บราวน์",
		FirstNameEN:  "Michael",
		MiddleNameEN: "David",
		LastNameEN:   "Brown",
		DateOfBirth:  "1991-09-03",
		PhoneNumber:  "0828889999",
		Email:        "michael.brown@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00018",
		NationalID:   "",
		PassportID:   "JP554433221",
		FirstNameTH:  "เคนจิ",
		MiddleNameTH: "",
		LastNameTH:   "ซาโต้",
		FirstNameEN:  "Kenji",
		MiddleNameEN: "",
		LastNameEN:   "Sato",
		DateOfBirth:  "1987-03-29",
		PhoneNumber:  "0829990000",
		Email:        "kenji.sato@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00019",
		NationalID:   "1100504455668",
		PassportID:   "",
		FirstNameTH:  "ชัยวัฒน์",
		MiddleNameTH: "",
		LastNameTH:   "สว่างจิตต์",
		FirstNameEN:  "Chaiwat",
		MiddleNameEN: "",
		LastNameEN:   "Sawangjit",
		DateOfBirth:  "2001-07-07",
		PhoneNumber:  "0831112222",
		Email:        "chaiwat.s@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00020",
		NationalID:   "1100505566779",
		PassportID:   "",
		FirstNameTH:  "ชลธิชา",
		MiddleNameTH: "",
		LastNameTH:   "สว่างจิตต์",
		FirstNameEN:  "Chonthicha",
		MiddleNameEN: "",
		LastNameEN:   "Sawangjit",
		DateOfBirth:  "2004-10-15",
		PhoneNumber:  "0832223333",
		Email:        "chonthicha.s@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00021",
		NationalID:   "1100506677880",
		PassportID:   "",
		FirstNameTH:  "ธนดล",
		MiddleNameTH: "",
		LastNameTH:   "พงษ์พาณิชย์",
		FirstNameEN:  "Thanadol",
		MiddleNameEN: "",
		LastNameEN:   "Pongpanich",
		DateOfBirth:  "2012-04-18",
		PhoneNumber:  "0833334444",
		Email:        "parent.thanadol@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00022",
		NationalID:   "1100507788991",
		PassportID:   "",
		FirstNameTH:  "ธนพร",
		MiddleNameTH: "",
		LastNameTH:   "พงษ์พาณิชย์",
		FirstNameEN:  "Thanaporn",
		MiddleNameEN: "",
		LastNameEN:   "Pongpanich",
		DateOfBirth:  "2015-08-22",
		PhoneNumber:  "0834445555",
		Email:        "parent.thanaporn@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00023",
		NationalID:   "1100508899002",
		PassportID:   "TH8877665",
		FirstNameTH:  "พิชญา",
		MiddleNameTH: "",
		LastNameTH:   "อัครเดช",
		FirstNameEN:  "Pitchaya",
		MiddleNameEN: "",
		LastNameEN:   "Akkaradech",
		DateOfBirth:  "1993-12-12",
		PhoneNumber:  "0835556666",
		Email:        "pitchaya.a@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00024",
		NationalID:   "1100509900113",
		PassportID:   "",
		FirstNameTH:  "รัชพล",
		MiddleNameTH: "",
		LastNameTH:   "อัครเดช",
		FirstNameEN:  "Ratchapol",
		MiddleNameEN: "",
		LastNameEN:   "Akkaradech",
		DateOfBirth:  "1989-05-30",
		PhoneNumber:  "0836667777",
		Email:        "ratchapol.a@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP001",
		PatientHN:    "P00025",
		NationalID:   "1100500011224",
		PassportID:   "",
		FirstNameTH:  "สุดาพร",
		MiddleNameTH: "",
		LastNameTH:   "เจริญสุข",
		FirstNameEN:  "Sudaporn",
		MiddleNameEN: "",
		LastNameEN:   "Charoensuk",
		DateOfBirth:  "1996-09-09",
		PhoneNumber:  "0837778888",
		Email:        "sudaporn.c@example.com",
		Gender:       "F",
	},

	// =========================================================================
	// HOSP002: โรงพยาบาลจุฬาลงกรณ์ (King Chulalongkorn Memorial Hospital) - 10 Patients
	// (Includes cross-hospital duplicate names for testing multi-tenant scoping)
	// =========================================================================
	{
		// Exact duplicate name & DOB of P00001 in HOSP001, but scoped to HOSP002!
		HospitalHN:   "HOSP002",
		PatientHN:    "P00026",
		NationalID:   "2100601234567",
		PassportID:   "",
		FirstNameTH:  "สมชาย",
		MiddleNameTH: "วิชัย",
		LastNameTH:   "ใจดี",
		FirstNameEN:  "Somchai",
		MiddleNameEN: "Wichai",
		LastNameEN:   "Jaidee",
		DateOfBirth:  "1985-04-12",
		PhoneNumber:  "0841112222",
		Email:        "somchai.chula@example.com",
		Gender:       "M",
	},
	{
		// Exact duplicate name of P00003 John Smith in HOSP001, but in HOSP002!
		HospitalHN:   "HOSP002",
		PatientHN:    "P00027",
		NationalID:   "",
		PassportID:   "US776655443",
		FirstNameTH:  "จอห์น",
		MiddleNameTH: "วิลเลียม",
		LastNameTH:   "สมิธ",
		FirstNameEN:  "John",
		MiddleNameEN: "William",
		LastNameEN:   "Smith",
		DateOfBirth:  "1978-08-15",
		PhoneNumber:  "0842223333",
		Email:        "john.smith.chula@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00028",
		NationalID:   "2100609876543",
		PassportID:   "",
		FirstNameTH:  "อนันต์",
		MiddleNameTH: "",
		LastNameTH:   "มั่นคง",
		FirstNameEN:  "Anan",
		MiddleNameEN: "",
		LastNameEN:   "Mankong",
		DateOfBirth:  "1995-02-18",
		PhoneNumber:  "0845678901",
		Email:        "anan.mankong@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00029",
		NationalID:   "2100602345678",
		PassportID:   "GB876543210",
		FirstNameTH:  "เอมิลี่",
		MiddleNameTH: "โรส",
		LastNameTH:   "คลาร์ก",
		FirstNameEN:  "Emily",
		MiddleNameEN: "Rose",
		LastNameEN:   "Clark",
		DateOfBirth:  "1992-06-30",
		PhoneNumber:  "0856789012",
		Email:        "emily.clark@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00030",
		NationalID:   "2100603456789",
		PassportID:   "",
		FirstNameTH:  "นภา",
		MiddleNameTH: "",
		LastNameTH:   "สดใส",
		FirstNameEN:  "Napha",
		MiddleNameEN: "",
		LastNameEN:   "Sodsai",
		DateOfBirth:  "1982-11-05",
		PhoneNumber:  "0843334444",
		Email:        "napha.sodsai@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00031",
		NationalID:   "2100604567890",
		PassportID:   "",
		FirstNameTH:  "ธนากร",
		MiddleNameTH: "",
		LastNameTH:   "รุ่งเรือง",
		FirstNameEN:  "Thanakorn",
		MiddleNameEN: "",
		LastNameEN:   "Rungruang",
		DateOfBirth:  "1979-03-17",
		PhoneNumber:  "0844445555",
		Email:        "thanakorn.r@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00032",
		NationalID:   "2100605678901",
		PassportID:   "",
		FirstNameTH:  "กมลวรรณ",
		MiddleNameTH: "",
		LastNameTH:   "บุญมี",
		FirstNameEN:  "Kamonwan",
		MiddleNameEN: "",
		LastNameEN:   "Boonmee",
		DateOfBirth:  "1990-08-28",
		PhoneNumber:  "0845556666",
		Email:        "kamonwan.b@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00033",
		NationalID:   "2100606789012",
		PassportID:   "",
		FirstNameTH:  "ธีรภัทร์",
		MiddleNameTH: "",
		LastNameTH:   "บุญมี",
		FirstNameEN:  "Theeraphat",
		MiddleNameEN: "",
		LastNameEN:   "Boonmee",
		DateOfBirth:  "1986-01-11",
		PhoneNumber:  "0846667777",
		Email:        "theeraphat.b@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00034",
		NationalID:   "",
		PassportID:   "FR334455667",
		FirstNameTH:  "โคลเอ้",
		MiddleNameTH: "",
		LastNameTH:   "ดูบัวส์",
		FirstNameEN:  "Chloe",
		MiddleNameEN: "",
		LastNameEN:   "Dubois",
		DateOfBirth:  "1997-04-19",
		PhoneNumber:  "0847778888",
		Email:        "chloe.dubois@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP002",
		PatientHN:    "P00035",
		NationalID:   "2100607890123",
		PassportID:   "",
		FirstNameTH:  "วรินทร",
		MiddleNameTH: "",
		LastNameTH:   "เลิศวิริยะ",
		FirstNameEN:  "Warinthorn",
		MiddleNameEN: "",
		LastNameEN:   "Lertwiriya",
		DateOfBirth:  "1981-12-24",
		PhoneNumber:  "0848889999",
		Email:        "warinthorn.l@example.com",
		Gender:       "F",
	},

	// =========================================================================
	// HOSP003: โรงพยาบาลรามาธิบดี (Ramathibodi Hospital) - 5 Patients
	// =========================================================================
	{
		HospitalHN:   "HOSP003",
		PatientHN:    "P00036",
		NationalID:   "3100701234567",
		PassportID:   "",
		FirstNameTH:  "ประเสริฐ",
		MiddleNameTH: "",
		LastNameTH:   "ยิ่งเจริญ",
		FirstNameEN:  "Prasert",
		MiddleNameEN: "",
		LastNameEN:   "Yingcharoen",
		DateOfBirth:  "1968-05-09",
		PhoneNumber:  "0851112222",
		Email:        "prasert.y@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP003",
		PatientHN:    "P00037",
		NationalID:   "3100702345678",
		PassportID:   "",
		FirstNameTH:  "มยุรี",
		MiddleNameTH: "",
		LastNameTH:   "ศรีสุข",
		FirstNameEN:  "Mayuree",
		MiddleNameEN: "",
		LastNameEN:   "Srisuk",
		DateOfBirth:  "1974-09-15",
		PhoneNumber:  "0852223333",
		Email:        "mayuree.s@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP003",
		PatientHN:    "P00038",
		NationalID:   "",
		PassportID:   "US556677889",
		FirstNameTH:  "เดวิด",
		MiddleNameTH: "โรเบิร์ต",
		LastNameTH:   "มิลเลอร์",
		FirstNameEN:  "David",
		MiddleNameEN: "Robert",
		LastNameEN:   "Miller",
		DateOfBirth:  "1983-10-31",
		PhoneNumber:  "0853334444",
		Email:        "david.miller@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP003",
		PatientHN:    "P00039",
		NationalID:   "3100703456789",
		PassportID:   "",
		FirstNameTH:  "พิมพ์ชนก",
		MiddleNameTH: "",
		LastNameTH:   "แก้วมณี",
		FirstNameEN:  "Pimchanok",
		MiddleNameEN: "",
		LastNameEN:   "Kaewmanee",
		DateOfBirth:  "1999-07-21",
		PhoneNumber:  "0854445555",
		Email:        "pimchanok.k@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP003",
		PatientHN:    "P00040",
		NationalID:   "3100704567890",
		PassportID:   "",
		FirstNameTH:  "วรวิทย์",
		MiddleNameTH: "",
		LastNameTH:   "สิทธิโชค",
		FirstNameEN:  "Worawit",
		MiddleNameEN: "",
		LastNameEN:   "Sitthichok",
		DateOfBirth:  "1991-03-04",
		PhoneNumber:  "0855556666",
		Email:        "worawit.s@example.com",
		Gender:       "M",
	},

	// =========================================================================
	// HOSP004 (Bangkok Hospital) & HOSP005 (Bumrungrad Hospital) - 5 Patients
	// (Medical tourism & international expat patients)
	// =========================================================================
	{
		HospitalHN:   "HOSP004",
		PatientHN:    "P00041",
		NationalID:   "",
		PassportID:   "DE123456789",
		FirstNameTH:  "ฮันส์",
		MiddleNameTH: "",
		LastNameTH:   "ชมิดท์",
		FirstNameEN:  "Hans",
		MiddleNameEN: "",
		LastNameEN:   "Schmidt",
		DateOfBirth:  "1970-11-11",
		PhoneNumber:  "0861112222",
		Email:        "hans.schmidt@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP004",
		PatientHN:    "P00042",
		NationalID:   "",
		PassportID:   "RU987654321",
		FirstNameTH:  "เอเลน่า",
		MiddleNameTH: "",
		LastNameTH:   "เปโตรวา",
		FirstNameEN:  "Elena",
		MiddleNameEN: "",
		LastNameEN:   "Petrova",
		DateOfBirth:  "1989-08-08",
		PhoneNumber:  "0862223333",
		Email:        "elena.petrova@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP005",
		PatientHN:    "P00043",
		NationalID:   "",
		PassportID:   "SG112233445",
		FirstNameTH:  "เฉิน",
		MiddleNameTH: "",
		LastNameTH:   "เหว่ย",
		FirstNameEN:  "Chen",
		MiddleNameEN: "",
		LastNameEN:   "Wei",
		DateOfBirth:  "1985-02-27",
		PhoneNumber:  "0863334444",
		Email:        "chen.wei@example.com",
		Gender:       "M",
	},
	{
		HospitalHN:   "HOSP005",
		PatientHN:    "P00044",
		NationalID:   "",
		PassportID:   "AE778899001",
		FirstNameTH:  "ฟาติมา",
		MiddleNameTH: "",
		LastNameTH:   "อัล-มันซูร์",
		FirstNameEN:  "Fatima",
		MiddleNameEN: "",
		LastNameEN:   "Al-Mansoor",
		DateOfBirth:  "1994-06-16",
		PhoneNumber:  "0864445555",
		Email:        "fatima.almansoor@example.com",
		Gender:       "F",
	},
	{
		HospitalHN:   "HOSP005",
		PatientHN:    "P00045",
		NationalID:   "",
		PassportID:   "AU445566778",
		FirstNameTH:  "เอ็มม่า",
		MiddleNameTH: "เกรซ",
		LastNameTH:   "วิลสัน",
		FirstNameEN:  "Emma",
		MiddleNameEN: "Grace",
		LastNameEN:   "Wilson",
		DateOfBirth:  "1993-01-20",
		PhoneNumber:  "0865556666",
		Email:        "emma.wilson@example.com",
		Gender:       "F",
	},
}

// SeedPatients inserts or updates patient mockup records in a transaction.
func SeedPatients(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("database connection is nil")
	}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	// Map hospital HN to ID
	hospMap := make(map[string]string)
	rows, err := tx.QueryContext(ctx, "SELECT id, hn FROM hospital")
	if err != nil {
		return fmt.Errorf("failed to query hospitals: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var id, hn string
		if err := rows.Scan(&id, &hn); err != nil {
			return fmt.Errorf("scan hospital row: %w", err)
		}
		hospMap[hn] = id
	}

	insertQuery := `
		INSERT INTO patient (
			hospital_id,
			patient_hn,
			national_id,
			passport_id,
			first_name_th,
			middle_name_th,
			last_name_th,
			first_name_en,
			middle_name_en,
			last_name_en,
			date_of_birth,
			phone_number,
			email,
			gender
		) VALUES (
			$1, $2,
			NULLIF($3, ''), NULLIF($4, ''),
			NULLIF($5, ''), NULLIF($6, ''), NULLIF($7, ''),
			NULLIF($8, ''), NULLIF($9, ''), NULLIF($10, ''),
			$11,
			NULLIF($12, ''), NULLIF($13, ''),
			$14
		)
		ON CONFLICT (hospital_id, patient_hn) DO UPDATE SET
			national_id = EXCLUDED.national_id,
			passport_id = EXCLUDED.passport_id,
			first_name_th = EXCLUDED.first_name_th,
			middle_name_th = EXCLUDED.middle_name_th,
			last_name_th = EXCLUDED.last_name_th,
			first_name_en = EXCLUDED.first_name_en,
			middle_name_en = EXCLUDED.middle_name_en,
			last_name_en = EXCLUDED.last_name_en,
			date_of_birth = EXCLUDED.date_of_birth,
			phone_number = EXCLUDED.phone_number,
			email = EXCLUDED.email,
			gender = EXCLUDED.gender,
			updated_at = CURRENT_TIMESTAMP
	`

	stmt, err := tx.PrepareContext(ctx, insertQuery)
	if err != nil {
		return fmt.Errorf("failed to prepare statement: %w", err)
	}
	defer stmt.Close()

	for _, p := range DefaultPatients {
		hospID, exists := hospMap[p.HospitalHN]
		if !exists {
			continue // skip if hospital not found
		}

		dob, err := time.Parse("2006-01-02", p.DateOfBirth)
		if err != nil {
			return fmt.Errorf("invalid dob for %s: %w", p.PatientHN, err)
		}

		if _, err := stmt.ExecContext(
			ctx,
			hospID,
			p.PatientHN,
			p.NationalID,
			p.PassportID,
			p.FirstNameTH,
			p.MiddleNameTH,
			p.LastNameTH,
			p.FirstNameEN,
			p.MiddleNameEN,
			p.LastNameEN,
			dob,
			p.PhoneNumber,
			p.Email,
			p.Gender,
		); err != nil {
			return fmt.Errorf("failed to seed patient hn=%s: %w", p.PatientHN, err)
		}
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("failed to commit patient seed transaction: %w", err)
	}

	log.Printf("[INFO] Successfully seeded %d patient records into 'patient' table", len(DefaultPatients))
	return nil
}
