package middleware

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"

	"hospital-middleware/internal/auth"
	"hospital-middleware/internal/service"

	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
)

// ContentTypeProblemJSON is the MIME media type defined by RFC 7807.
const ContentTypeProblemJSON = "application/problem+json"

// ProblemDetails represents an RFC 7807 Problem Details object for HTTP APIs.
// Specification: https://datatracker.ietf.org/doc/html/rfc7807
type ProblemDetails struct {
	Type     string `json:"type"`               // URI reference that identifies the problem type
	Title    string `json:"title"`              // Short, human-readable summary of the problem type
	Status   int    `json:"status"`             // HTTP status code generated by origin server
	Detail   string `json:"detail,omitempty"`   // Human-readable explanation specific to this occurrence
	Instance string `json:"instance,omitempty"` // URI reference that identifies the specific occurrence
	Error    string `json:"error,omitempty"`    // Backward-compatible alias for detail
}

// AppError represents an application-specific error with RFC 7807 parameters.
type AppError struct {
	StatusCode int
	Type       string
	Title      string
	Message    string
	Err        error
}

func (e *AppError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	if e.Err != nil {
		return e.Err.Error()
	}
	return "internal error"
}

func (e *AppError) Unwrap() error {
	return e.Err
}

// NewAppError creates a new AppError instance.
func NewAppError(statusCode int, message string, err ...error) *AppError {
	var underlying error
	if len(err) > 0 {
		underlying = err[0]
	}
	return &AppError{
		StatusCode: statusCode,
		Message:    message,
		Err:        underlying,
	}
}

// NewProblemDetails constructs a ProblemDetails response conforming to RFC 7807.
func NewProblemDetails(status int, detail string, instance string, problemType ...string) ProblemDetails {
	t := "about:blank"
	if len(problemType) > 0 && problemType[0] != "" {
		t = problemType[0]
	}

	title := http.StatusText(status)
	if title == "" {
		title = "Error"
	}

	return ProblemDetails{
		Type:     t,
		Title:    title,
		Status:   status,
		Detail:   detail,
		Instance: instance,
		Error:    detail,
	}
}

// ErrorHandler is a centralized Gin middleware conforming to RFC 7807 (Problem Details for HTTP APIs).
func ErrorHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()

		// If response is already written, do nothing.
		if c.Writer.Written() {
			return
		}

		if len(c.Errors) == 0 {
			return
		}

		lastErr := c.Errors.Last()
		err := lastErr.Err
		instance := c.Request.URL.Path

		var appErr *AppError
		var valErr validator.ValidationErrors
		var jsonSyntaxErr *json.SyntaxError
		var jsonUnmarshalErr *json.UnmarshalTypeError

		var problem ProblemDetails

		switch {
		// Business domain errors
		case errors.Is(err, service.ErrHospitalNotFound):
			problem = NewProblemDetails(http.StatusBadRequest, "hospital not found", instance, "/errors/hospital-not-found")

		case errors.Is(err, service.ErrStaffAlreadyExists):
			problem = NewProblemDetails(http.StatusConflict, "staff already exists", instance, "/errors/staff-already-exists")

		case errors.Is(err, service.ErrInvalidCredentials),
			errors.Is(err, auth.ErrInvalidToken):
			problem = NewProblemDetails(http.StatusUnauthorized, "invalid username or password", instance, "/errors/unauthorized")

		case errors.Is(err, service.ErrEmptySearchCriteria),
			errors.Is(err, service.ErrInvalidDateOfBirth),
			errors.Is(err, service.ErrInvalidPatientID):
			problem = NewProblemDetails(http.StatusBadRequest, err.Error(), instance, "/errors/validation-error")

		case errors.Is(err, service.ErrPatientNotFound):
			problem = NewProblemDetails(http.StatusNotFound, "patient not found", instance, "/errors/patient-not-found")

		case errors.Is(err, service.ErrInvalidHospitalID):
			problem = NewProblemDetails(http.StatusUnauthorized, "hospital ID is required", instance, "/errors/unauthorized")

		// Custom application errors
		case errors.As(err, &appErr):
			title := appErr.Title
			if title == "" {
				title = http.StatusText(appErr.StatusCode)
			}
			t := appErr.Type
			if t == "" {
				t = "about:blank"
			}
			problem = ProblemDetails{
				Type:     t,
				Title:    title,
				Status:   appErr.StatusCode,
				Detail:   appErr.Message,
				Instance: instance,
				Error:    appErr.Message,
			}

		// Request binding and validation errors
		case lastErr.Type == gin.ErrorTypeBind,
			errors.As(err, &valErr),
			errors.As(err, &jsonSyntaxErr),
			errors.As(err, &jsonUnmarshalErr),
			errors.Is(err, io.EOF):
			problem = NewProblemDetails(http.StatusBadRequest, err.Error(), instance, "/errors/validation-error")

		// Internal server errors
		default:
			problem = NewProblemDetails(http.StatusInternalServerError, "failed to query hospital", instance, "/errors/internal-error")
		}

		c.Header("Content-Type", ContentTypeProblemJSON)
		c.AbortWithStatusJSON(problem.Status, problem)
	}
}
