// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check server and database connectivity status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness and Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-internal_handlers_HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-internal_handlers_HealthResponse"
                        }
                    }
                }
            }
        },
        "/patient/search": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Search patients within the authenticated staff member's hospital. Multiple criteria are combined with AND logic. At least one search criterion must be provided. Supports partial matching for names and email, exact matching for IDs and phone, and YYYY-MM-DD format for date of birth.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Search patients",
                "parameters": [
                    {
                        "description": "Patient search criteria payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.PatientSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful search response with list of matching patients",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-internal_handlers_PatientSearchOutput"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid parameters or empty search criteria",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: missing or invalid session cookie",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/patient/search/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Search and retrieve specific patient details by Thai National ID (13 digits) or Passport ID within the authenticated staff member's hospital.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Search patient by National ID or Passport ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"1100501234567\"",
                        "description": "National ID (13 digits) or Passport ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with patient details",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-hospital-middleware_internal_service_PatientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid national_id or passport_id format",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: missing or invalid session cookie",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Not found: patient does not exist",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_middleware.ProblemDetails"
                        }
                    }
                }
            }
        },
        "/staff/create": {
            "post": {
                "description": "Register staff with hospital affiliation, username, and secure password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Create a new hospital staff member",
                "parameters": [
                    {
                        "description": "Staff registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.CreateStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-internal_handlers_CreateStaffOutput"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Username already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/staff/login": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Authenticate staff member and issue session cookie with JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Staff"
                ],
                "summary": "Staff login authentication",
                "parameters": [
                    {
                        "description": "Staff login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.LoginStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hospital-middleware_internal_response.Response-internal_handlers_LoginStaffOutput"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hospital-middleware_internal_middleware.ProblemDetails": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Human-readable explanation specific to this occurrence",
                    "type": "string"
                },
                "error": {
                    "description": "Backward-compatible alias for detail",
                    "type": "string"
                },
                "instance": {
                    "description": "URI reference that identifies the specific occurrence",
                    "type": "string"
                },
                "status": {
                    "description": "HTTP status code generated by origin server",
                    "type": "integer"
                },
                "title": {
                    "description": "Short, human-readable summary of the problem type",
                    "type": "string"
                },
                "type": {
                    "description": "URI reference that identifies the problem type",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_response.Response-hospital-middleware_internal_service_PatientResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/hospital-middleware_internal_service.PatientResponse"
                        }
                    ]
                },
                "message": {
                    "description": "Human-readable status message",
                    "type": "string"
                },
                "status": {
                    "description": "\"success\"",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_response.Response-internal_handlers_CreateStaffOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_handlers.CreateStaffOutput"
                        }
                    ]
                },
                "message": {
                    "description": "Human-readable status message",
                    "type": "string"
                },
                "status": {
                    "description": "\"success\"",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_response.Response-internal_handlers_HealthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_handlers.HealthResponse"
                        }
                    ]
                },
                "message": {
                    "description": "Human-readable status message",
                    "type": "string"
                },
                "status": {
                    "description": "\"success\"",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_response.Response-internal_handlers_LoginStaffOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_handlers.LoginStaffOutput"
                        }
                    ]
                },
                "message": {
                    "description": "Human-readable status message",
                    "type": "string"
                },
                "status": {
                    "description": "\"success\"",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_response.Response-internal_handlers_PatientSearchOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Payload data",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_handlers.PatientSearchOutput"
                        }
                    ]
                },
                "message": {
                    "description": "Human-readable status message",
                    "type": "string"
                },
                "status": {
                    "description": "\"success\"",
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_service.PatientResponse": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "description": "Date of birth formatted as YYYY-MM-DD",
                    "type": "string",
                    "example": "2004-10-15"
                },
                "email": {
                    "description": "Contact email address",
                    "type": "string",
                    "example": "chonthicha.s@example.com"
                },
                "first_name_en": {
                    "description": "Patient first name in English",
                    "type": "string",
                    "example": "Chonthicha"
                },
                "first_name_th": {
                    "description": "Patient first name in Thai",
                    "type": "string",
                    "example": "ชลธิชา"
                },
                "gender": {
                    "description": "Biological gender ('M' for Male, 'F' for Female, 'O' for Other)",
                    "type": "string",
                    "example": "F"
                },
                "id": {
                    "description": "Unique identifier (UUID) of the patient record",
                    "type": "string",
                    "example": "e7b23c21-1234-4567-89ab-cdef01234567"
                },
                "last_name_en": {
                    "description": "Patient last name in English",
                    "type": "string",
                    "example": "Sawangjit"
                },
                "last_name_th": {
                    "description": "Patient last name in Thai",
                    "type": "string",
                    "example": "สว่างจิตต์"
                },
                "middle_name_en": {
                    "description": "Patient middle name in English (optional)",
                    "type": "string",
                    "example": ""
                },
                "middle_name_th": {
                    "description": "Patient middle name in Thai (optional)",
                    "type": "string",
                    "example": ""
                },
                "national_id": {
                    "description": "13-digit Thai National Identification Number",
                    "type": "string",
                    "example": "1100505566779"
                },
                "passport_id": {
                    "description": "Passport number for foreign patients",
                    "type": "string",
                    "example": ""
                },
                "patient_hn": {
                    "description": "Hospital Number (HN) assigned to the patient within the hospital",
                    "type": "string",
                    "example": "P00020"
                },
                "phone_number": {
                    "description": "Contact telephone number",
                    "type": "string",
                    "example": "0832223333"
                }
            }
        },
        "hospital-middleware_internal_service.SessionInfoResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                }
            }
        },
        "hospital-middleware_internal_service.StaffInfoResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "hospital_hn": {
                    "type": "string"
                },
                "hospital_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.CreateStaffOutput": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/hospital-middleware_internal_service.SessionInfoResponse"
                },
                "staff": {
                    "$ref": "#/definitions/hospital-middleware_internal_service.StaffInfoResponse"
                }
            }
        },
        "internal_handlers.CreateStaffRequest": {
            "type": "object",
            "required": [
                "hospital",
                "password",
                "username"
            ],
            "properties": {
                "hospital": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "connected"
                },
                "error": {
                    "type": "string",
                    "example": ""
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "internal_handlers.LoginStaffOutput": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/hospital-middleware_internal_service.SessionInfoResponse"
                },
                "staff": {
                    "$ref": "#/definitions/hospital-middleware_internal_service.StaffInfoResponse"
                }
            }
        },
        "internal_handlers.LoginStaffRequest": {
            "type": "object",
            "required": [
                "hospital",
                "password",
                "username"
            ],
            "properties": {
                "hospital": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.PatientSearchOutput": {
            "type": "object",
            "properties": {
                "patients": {
                    "description": "List of matched patient records",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hospital-middleware_internal_service.PatientResponse"
                    }
                },
                "total": {
                    "description": "Total count of patients matching the criteria",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_handlers.PatientSearchRequest": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "description": "Date of birth formatted as YYYY-MM-DD (วันเกิด รูปแบบ YYYY-MM-DD)",
                    "type": "string",
                    "example": ""
                },
                "email": {
                    "description": "Contact email address (supports case-insensitive partial match)",
                    "type": "string",
                    "example": ""
                },
                "first_name": {
                    "description": "Patient first name in Thai or English (supports case-insensitive partial match)",
                    "type": "string",
                    "example": ""
                },
                "last_name": {
                    "description": "Patient last name in Thai or English (supports case-insensitive partial match)",
                    "type": "string",
                    "example": ""
                },
                "middle_name": {
                    "description": "Patient middle name in Thai or English (supports case-insensitive partial match)",
                    "type": "string",
                    "example": ""
                },
                "national_id": {
                    "description": "13-digit Thai Citizen Identification Number (เลขบัตรประชาชน 13 หลัก)",
                    "type": "string",
                    "example": "1100505566779"
                },
                "passport_id": {
                    "description": "Passport number for foreign patients (เลขที่หนังสือเดินทาง)",
                    "type": "string",
                    "example": ""
                },
                "phone_number": {
                    "description": "Contact telephone number (exact match)",
                    "type": "string",
                    "example": ""
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "description": "Session token cookie for authenticated endpoints.",
            "type": "apiKey",
            "name": "session_token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hospital Middleware API",
	Description:      "Middleware service handling staff authentication and hospital integrations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
